/**
 * AutobahnWarning automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnWarning {
    @JsonProperty("id")
    private String id;

    @JsonProperty("blocked")
    private Boolean blocked;

    @JsonProperty("future")
    private Boolean future;

    @JsonProperty("title")
    private String title;

    @JsonProperty("subtitle")
    private String subtitle;

    @JsonProperty("description")
    private java.util.List<String> description;

    @JsonProperty("startDate")
    private java.time.LocalDateTime startDate;

    @JsonProperty("coordinate")
    private AutobahnCoordinate coordinate;

    @JsonProperty("lineString")
    private java.util.List<AutobahnCoordinate> lineString;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }

    public Boolean getBlocked() {
        return this.blocked;
    }

    public void setFuture(Boolean future) {
        this.future = future;
    }

    public Boolean getFuture() {
        return this.future;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return this.title;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public String getSubtitle() {
        return this.subtitle;
    }

    public void setDescription(java.util.List<String> description) {
        this.description = description;
    }

    public java.util.List<String> getDescription() {
        return this.description;
    }

    public void setStartDate(java.time.LocalDateTime startDate) {
        this.startDate = startDate;
    }

    public java.time.LocalDateTime getStartDate() {
        return this.startDate;
    }

    public void setCoordinate(AutobahnCoordinate coordinate) {
        this.coordinate = coordinate;
    }

    public AutobahnCoordinate getCoordinate() {
        return this.coordinate;
    }

    public void setLineString(java.util.List<AutobahnCoordinate> lineString) {
        this.lineString = lineString;
    }

    public java.util.List<AutobahnCoordinate> getLineString() {
        return this.lineString;
    }
}

