/**
 * AutobahnCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnCollection {
    private java.util.List<String> roads;

    @JsonSetter("roads")
    public void setRoads(java.util.List<String> roads) {
        this.roads = roads;
    }

    @JsonGetter("roads")
    public java.util.List<String> getRoads() {
        return this.roads;
    }
}

