/**
 * AutobahnParkingLorry automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnParkingLorry {
    @JsonProperty("id")
    private String id;

    @JsonProperty("title")
    private String title;

    @JsonProperty("subtitle")
    private String subtitle;

    @JsonProperty("description")
    private java.util.List<String> description;

    @JsonProperty("coordinate")
    private AutobahnCoordinate coordinate;

    @JsonProperty("features")
    private java.util.List<String> features;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return this.title;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public String getSubtitle() {
        return this.subtitle;
    }

    public void setDescription(java.util.List<String> description) {
        this.description = description;
    }

    public java.util.List<String> getDescription() {
        return this.description;
    }

    public void setCoordinate(AutobahnCoordinate coordinate) {
        this.coordinate = coordinate;
    }

    public AutobahnCoordinate getCoordinate() {
        return this.coordinate;
    }

    public void setFeatures(java.util.List<String> features) {
        this.features = features;
    }

    public java.util.List<String> getFeatures() {
        return this.features;
    }
}

