/**
 * AutobahnParkingLorryCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnParkingLorryCollection {
    @JsonProperty("entries")
    private java.util.List<AutobahnParkingLorry> entries;


    public void setEntries(java.util.List<AutobahnParkingLorry> entries) {
        this.entries = entries;
    }

    public java.util.List<AutobahnParkingLorry> getEntries() {
        return this.entries;
    }
}

