/**
 * AutobahnTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import app.sdkgen.client.Exception.ClientException;
import app.sdkgen.client.Exception.UnknownStatusCodeException;
import app.sdkgen.client.Parser;
import app.sdkgen.client.TagAbstract;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.hc.client5.http.classic.HttpClient;
import org.apache.hc.client5.http.classic.methods.*;
import org.apache.hc.client5.http.entity.UrlEncodedFormEntity;
import org.apache.hc.core5.http.ContentType;
import org.apache.hc.core5.http.io.entity.*;
import org.apache.hc.core5.net.URIBuilder;
import org.apache.hc.core5.net.URLEncodedUtils;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AutobahnTag extends TagAbstract {
    public AutobahnTag(HttpClient httpClient, ObjectMapper objectMapper, Parser parser) {
        super(httpClient, objectMapper, parser);
    }

    public AutobahnChargingStationTag chargingStation()
    {
        return new AutobahnChargingStationTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public AutobahnClosureTag closure()
    {
        return new AutobahnClosureTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public AutobahnParkingLorryTag parkingLorry()
    {
        return new AutobahnParkingLorryTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }

    public AutobahnWarningTag warning()
    {
        return new AutobahnWarningTag(
            this.httpClient,
            this.objectMapper,
            this.parser
        );
    }


    /**
     * Returns all available autobahns
     */
    public AutobahnCollection getAll() throws ClientException {
        try {
            Map<String, Object> pathParams = new HashMap<>();

            Map<String, Object> queryParams = new HashMap<>();

            List<String> queryStructNames = new ArrayList<>();

            URIBuilder builder = new URIBuilder(this.parser.url("/autobahn", pathParams));
            this.parser.query(builder, queryParams, queryStructNames);

            HttpGet request = new HttpGet(builder.build());


            return this.httpClient.execute(request, response -> {
                if (response.getCode() >= 200 && response.getCode() <= 299) {
                    var data = this.parser.parse(EntityUtils.toString(response.getEntity()), new TypeReference<AutobahnCollection>(){});

                    return data;
                }

                var statusCode = response.getCode();
                if (statusCode == 400) {
                    var data = this.parser.parse(EntityUtils.toString(response.getEntity()), new TypeReference<Response>(){});

                    throw new ResponseException(data);
                }

                if (statusCode == 404) {
                    var data = this.parser.parse(EntityUtils.toString(response.getEntity()), new TypeReference<Response>(){});

                    throw new ResponseException(data);
                }

                if (statusCode == 500) {
                    var data = this.parser.parse(EntityUtils.toString(response.getEntity()), new TypeReference<Response>(){});

                    throw new ResponseException(data);
                }

                throw new UnknownStatusCodeException("The server returned an unknown status code: " + statusCode);
            });
        } catch (ClientException e) {
            throw e;
        } catch (URISyntaxException | IOException e) {
            throw new ClientException("An unknown error occurred: " + e.getMessage(), e);
        }
    }



}
