/**
 * AutobahnChargingStationCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnChargingStationCollection {
    @JsonProperty("entries")
    private java.util.List<AutobahnChargingStation> entries;


    public void setEntries(java.util.List<AutobahnChargingStation> entries) {
        this.entries = entries;
    }

    public java.util.List<AutobahnChargingStation> getEntries() {
        return this.entries;
    }
}

