/**
 * AutobahnWarningCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnWarningCollection {
    @JsonProperty("entries")
    private java.util.List<AutobahnWarning> entries;


    public void setEntries(java.util.List<AutobahnWarning> entries) {
        this.entries = entries;
    }

    public java.util.List<AutobahnWarning> getEntries() {
        return this.entries;
    }
}

