/**
 * AutobahnCoordinate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class AutobahnCoordinate {
    private String lat;
    private String _long;
    @JsonSetter("lat")
    public void setLat(String lat) {
        this.lat = lat;
    }
    @JsonGetter("lat")
    public String getLat() {
        return this.lat;
    }
    @JsonSetter("long")
    public void setLong(String _long) {
        this._long = _long;
    }
    @JsonGetter("long")
    public String getLong() {
        return this._long;
    }
}
