/**
 * AutobahnCoordinate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnCoordinate {
    @JsonProperty("lat")
    private String lat;

    @JsonProperty("long")
    private String _long;


    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getLat() {
        return this.lat;
    }

    public void setLong(String _long) {
        this._long = _long;
    }

    public String getLong() {
        return this._long;
    }
}

