/**
 * AutobahnParkingLorry automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class AutobahnParkingLorry {
    private String id;
    private String title;
    private String subtitle;
    private List<String> description;
    private AutobahnCoordinate coordinate;
    private List<String> features;
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }
    @JsonGetter("id")
    public String getId() {
        return this.id;
    }
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }
    @JsonGetter("title")
    public String getTitle() {
        return this.title;
    }
    @JsonSetter("subtitle")
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }
    @JsonGetter("subtitle")
    public String getSubtitle() {
        return this.subtitle;
    }
    @JsonSetter("description")
    public void setDescription(List<String> description) {
        this.description = description;
    }
    @JsonGetter("description")
    public List<String> getDescription() {
        return this.description;
    }
    @JsonSetter("coordinate")
    public void setCoordinate(AutobahnCoordinate coordinate) {
        this.coordinate = coordinate;
    }
    @JsonGetter("coordinate")
    public AutobahnCoordinate getCoordinate() {
        return this.coordinate;
    }
    @JsonSetter("features")
    public void setFeatures(List<String> features) {
        this.features = features;
    }
    @JsonGetter("features")
    public List<String> getFeatures() {
        return this.features;
    }
}
