/**
 * AutobahnCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class AutobahnCollection {
    private List<String> roads;
    @JsonSetter("roads")
    public void setRoads(List<String> roads) {
        this.roads = roads;
    }
    @JsonGetter("roads")
    public List<String> getRoads() {
        return this.roads;
    }
}
