/**
 * AutobahnClosureCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnClosureCollection {
    private java.util.List<AutobahnClosure> entries;

    @JsonSetter("entries")
    public void setEntries(java.util.List<AutobahnClosure> entries) {
        this.entries = entries;
    }

    @JsonGetter("entries")
    public java.util.List<AutobahnClosure> getEntries() {
        return this.entries;
    }
}

