/**
 * AutobahnClosureCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class AutobahnClosureCollection {
    @JsonProperty("entries")
    private java.util.List<AutobahnClosure> entries;


    public void setEntries(java.util.List<AutobahnClosure> entries) {
        this.entries = entries;
    }

    public java.util.List<AutobahnClosure> getEntries() {
        return this.entries;
    }
}

