/**
 * AutobahnParkingLorryCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class AutobahnParkingLorryCollection {
    private List<AutobahnParkingLorry> entries;
    @JsonSetter("entries")
    public void setEntries(List<AutobahnParkingLorry> entries) {
        this.entries = entries;
    }
    @JsonGetter("entries")
    public List<AutobahnParkingLorry> getEntries() {
        return this.entries;
    }
}
