/**
 * AutobahnClosureCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class AutobahnClosureCollection {
    private List<AutobahnClosure> entries;
    @JsonSetter("entries")
    public void setEntries(List<AutobahnClosure> entries) {
        this.entries = entries;
    }
    @JsonGetter("entries")
    public List<AutobahnClosure> getEntries() {
        return this.entries;
    }
}
