/**
 * BudgetCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class BudgetCollection {
    @JsonProperty("entries")
    private java.util.List<Budget> entries;


    public void setEntries(java.util.List<Budget> entries) {
        this.entries = entries;
    }

    public java.util.List<Budget> getEntries() {
        return this.entries;
    }
}

