/**
 * Budget automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class Budget {
    @JsonProperty("id")
    private String id;

    @JsonProperty("label")
    private String label;

    @JsonProperty("value")
    private Integer value;

    @JsonProperty("relativeToParentValue")
    private Integer relativeToParentValue;

    @JsonProperty("relativeValue")
    private Integer relativeValue;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getLabel() {
        return this.label;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

    public Integer getValue() {
        return this.value;
    }

    public void setRelativeToParentValue(Integer relativeToParentValue) {
        this.relativeToParentValue = relativeToParentValue;
    }

    public Integer getRelativeToParentValue() {
        return this.relativeToParentValue;
    }

    public void setRelativeValue(Integer relativeValue) {
        this.relativeValue = relativeValue;
    }

    public Integer getRelativeValue() {
        return this.relativeValue;
    }
}

