/**
 * BundestagMember automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class BundestagMember {
    @JsonProperty("id")
    private String id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("party")
    private String party;

    @JsonProperty("bioUrl")
    private String bioUrl;

    @JsonProperty("state")
    private String state;

    @JsonProperty("constituency")
    private BundestagConstituency constituency;

    @JsonProperty("elected")
    private String elected;

    @JsonProperty("photo")
    private String photo;

    @JsonProperty("photoLarge")
    private String photoLarge;

    @JsonProperty("photoLastChanged")
    private java.time.LocalDateTime photoLastChanged;

    @JsonProperty("lastChanged")
    private java.time.LocalDateTime lastChanged;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setParty(String party) {
        this.party = party;
    }

    public String getParty() {
        return this.party;
    }

    public void setBioUrl(String bioUrl) {
        this.bioUrl = bioUrl;
    }

    public String getBioUrl() {
        return this.bioUrl;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getState() {
        return this.state;
    }

    public void setConstituency(BundestagConstituency constituency) {
        this.constituency = constituency;
    }

    public BundestagConstituency getConstituency() {
        return this.constituency;
    }

    public void setElected(String elected) {
        this.elected = elected;
    }

    public String getElected() {
        return this.elected;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhotoLarge(String photoLarge) {
        this.photoLarge = photoLarge;
    }

    public String getPhotoLarge() {
        return this.photoLarge;
    }

    public void setPhotoLastChanged(java.time.LocalDateTime photoLastChanged) {
        this.photoLastChanged = photoLastChanged;
    }

    public java.time.LocalDateTime getPhotoLastChanged() {
        return this.photoLastChanged;
    }

    public void setLastChanged(java.time.LocalDateTime lastChanged) {
        this.lastChanged = lastChanged;
    }

    public java.time.LocalDateTime getLastChanged() {
        return this.lastChanged;
    }
}

