/**
 * BundestagMemberCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class BundestagMemberCollection {
    @JsonProperty("entries")
    private java.util.List<BundestagMember> entries;


    public void setEntries(java.util.List<BundestagMember> entries) {
        this.entries = entries;
    }

    public java.util.List<BundestagMember> getEntries() {
        return this.entries;
    }
}

