/**
 * BundesratMemberCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class BundesratMemberCollection {
    private java.util.List<BundesratMember> entries;

    @JsonSetter("entries")
    public void setEntries(java.util.List<BundesratMember> entries) {
        this.entries = entries;
    }

    @JsonGetter("entries")
    public java.util.List<BundesratMember> getEntries() {
        return this.entries;
    }
}

