/**
 * BundesratMemberCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BundesratMemberCollection {
    private List<BundesratMember> entries;
    @JsonSetter("entries")
    public void setEntries(List<BundesratMember> entries) {
        this.entries = entries;
    }
    @JsonGetter("entries")
    public List<BundesratMember> getEntries() {
        return this.entries;
    }
}
