/**
 * BundesratMember automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class BundesratMember {
    @JsonProperty("honorificTitle")
    private String honorificTitle;

    @JsonProperty("firstName")
    private String firstName;

    @JsonProperty("name")
    private String name;

    @JsonProperty("party")
    private String party;

    @JsonProperty("state")
    private String state;

    @JsonProperty("member")
    private Boolean member;

    @JsonProperty("designated")
    private Boolean designated;

    @JsonProperty("url")
    private String url;

    @JsonProperty("imagePath")
    private String imagePath;

    @JsonProperty("imageDate")
    private java.time.LocalDateTime imageDate;

    @JsonProperty("detail")
    private String detail;

    @JsonProperty("bio")
    private String bio;

    @JsonProperty("address")
    private String address;


    public void setHonorificTitle(String honorificTitle) {
        this.honorificTitle = honorificTitle;
    }

    public String getHonorificTitle() {
        return this.honorificTitle;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setParty(String party) {
        this.party = party;
    }

    public String getParty() {
        return this.party;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getState() {
        return this.state;
    }

    public void setMember(Boolean member) {
        this.member = member;
    }

    public Boolean getMember() {
        return this.member;
    }

    public void setDesignated(Boolean designated) {
        this.designated = designated;
    }

    public Boolean getDesignated() {
        return this.designated;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrl() {
        return this.url;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getImagePath() {
        return this.imagePath;
    }

    public void setImageDate(java.time.LocalDateTime imageDate) {
        this.imageDate = imageDate;
    }

    public java.time.LocalDateTime getImageDate() {
        return this.imageDate;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public String getDetail() {
        return this.detail;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getBio() {
        return this.bio;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress() {
        return this.address;
    }
}

