/**
 * City automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class City {
    @JsonProperty("id")
    private Integer id;

    @JsonProperty("state")
    private String state;

    @JsonProperty("rb")
    private String rb;

    @JsonProperty("district")
    private String district;

    @JsonProperty("verb")
    private String verb;

    @JsonProperty("gem")
    private String gem;

    @JsonProperty("name")
    private String name;

    @JsonProperty("zipCode")
    private String zipCode;

    @JsonProperty("area")
    private Integer area;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getState() {
        return this.state;
    }

    public void setRb(String rb) {
        this.rb = rb;
    }

    public String getRb() {
        return this.rb;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setVerb(String verb) {
        this.verb = verb;
    }

    public String getVerb() {
        return this.verb;
    }

    public void setGem(String gem) {
        this.gem = gem;
    }

    public String getGem() {
        return this.gem;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getZipCode() {
        return this.zipCode;
    }

    public void setArea(Integer area) {
        this.area = area;
    }

    public Integer getArea() {
        return this.area;
    }
}

