/**
 * City automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class City {
    private Integer id;
    private String state;
    private String rb;
    private String district;
    private String verb;
    private String gem;
    private String name;
    private String zipCode;
    private Integer area;
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }
    @JsonGetter("id")
    public Integer getId() {
        return this.id;
    }
    @JsonSetter("state")
    public void setState(String state) {
        this.state = state;
    }
    @JsonGetter("state")
    public String getState() {
        return this.state;
    }
    @JsonSetter("rb")
    public void setRb(String rb) {
        this.rb = rb;
    }
    @JsonGetter("rb")
    public String getRb() {
        return this.rb;
    }
    @JsonSetter("district")
    public void setDistrict(String district) {
        this.district = district;
    }
    @JsonGetter("district")
    public String getDistrict() {
        return this.district;
    }
    @JsonSetter("verb")
    public void setVerb(String verb) {
        this.verb = verb;
    }
    @JsonGetter("verb")
    public String getVerb() {
        return this.verb;
    }
    @JsonSetter("gem")
    public void setGem(String gem) {
        this.gem = gem;
    }
    @JsonGetter("gem")
    public String getGem() {
        return this.gem;
    }
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonGetter("name")
    public String getName() {
        return this.name;
    }
    @JsonSetter("zipCode")
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    @JsonGetter("zipCode")
    public String getZipCode() {
        return this.zipCode;
    }
    @JsonSetter("area")
    public void setArea(Integer area) {
        this.area = area;
    }
    @JsonGetter("area")
    public Integer getArea() {
        return this.area;
    }
}
