/**
 * Collection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class Collection<T> {
    @JsonProperty("totalResults")
    private Integer totalResults;

    @JsonProperty("startIndex")
    private Integer startIndex;

    @JsonProperty("itemsPerPage")
    private Integer itemsPerPage;

    @JsonProperty("entries")
    private java.util.List<T> entries;


    public void setTotalResults(Integer totalResults) {
        this.totalResults = totalResults;
    }

    public Integer getTotalResults() {
        return this.totalResults;
    }

    public void setStartIndex(Integer startIndex) {
        this.startIndex = startIndex;
    }

    public Integer getStartIndex() {
        return this.startIndex;
    }

    public void setItemsPerPage(Integer itemsPerPage) {
        this.itemsPerPage = itemsPerPage;
    }

    public Integer getItemsPerPage() {
        return this.itemsPerPage;
    }

    public void setEntries(java.util.List<T> entries) {
        this.entries = entries;
    }

    public java.util.List<T> getEntries() {
        return this.entries;
    }
}

