/**
 * District automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class District {
    @JsonProperty("id")
    private String id;

    @JsonProperty("state")
    private String state;

    @JsonProperty("type")
    private String type;

    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("NUTS3 classification")
    @JsonProperty("nuts3")
    private String nuts;

    @JsonPropertyDescription("Size of the area in km2")
    @JsonProperty("area")
    private Integer area;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getState() {
        return this.state;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getType() {
        return this.type;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setNuts(String nuts) {
        this.nuts = nuts;
    }

    public String getNuts() {
        return this.nuts;
    }

    public void setArea(Integer area) {
        this.area = area;
    }

    public Integer getArea() {
        return this.area;
    }
}

