/**
 * Job automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class Job {
    @JsonProperty("job")
    private String job;

    @JsonProperty("title")
    private String title;

    @JsonProperty("number")
    private String number;

    @JsonProperty("location")
    private JobLocation location;

    @JsonProperty("employer")
    private String employer;

    @JsonProperty("publishDate")
    private java.time.LocalDateTime publishDate;

    @JsonProperty("entranceDate")
    private java.time.LocalDateTime entranceDate;


    public void setJob(String job) {
        this.job = job;
    }

    public String getJob() {
        return this.job;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return this.title;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getNumber() {
        return this.number;
    }

    public void setLocation(JobLocation location) {
        this.location = location;
    }

    public JobLocation getLocation() {
        return this.location;
    }

    public void setEmployer(String employer) {
        this.employer = employer;
    }

    public String getEmployer() {
        return this.employer;
    }

    public void setPublishDate(java.time.LocalDateTime publishDate) {
        this.publishDate = publishDate;
    }

    public java.time.LocalDateTime getPublishDate() {
        return this.publishDate;
    }

    public void setEntranceDate(java.time.LocalDateTime entranceDate) {
        this.entranceDate = entranceDate;
    }

    public java.time.LocalDateTime getEntranceDate() {
        return this.entranceDate;
    }
}

