/**
 * JobLocation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class JobLocation {
    @JsonProperty("zip")
    private String zip;

    @JsonProperty("place")
    private String place;

    @JsonProperty("state")
    private String state;

    @JsonProperty("country")
    private String country;

    @JsonProperty("coordinate")
    private JobCoordinate coordinate;


    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getZip() {
        return this.zip;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public String getPlace() {
        return this.place;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getState() {
        return this.state;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCoordinate(JobCoordinate coordinate) {
        this.coordinate = coordinate;
    }

    public JobCoordinate getCoordinate() {
        return this.coordinate;
    }
}

