/**
 * JobLocation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class JobLocation {
    private String zip;
    private String place;
    private String state;
    private String country;
    private JobCoordinate coordinate;
    @JsonSetter("zip")
    public void setZip(String zip) {
        this.zip = zip;
    }
    @JsonGetter("zip")
    public String getZip() {
        return this.zip;
    }
    @JsonSetter("place")
    public void setPlace(String place) {
        this.place = place;
    }
    @JsonGetter("place")
    public String getPlace() {
        return this.place;
    }
    @JsonSetter("state")
    public void setState(String state) {
        this.state = state;
    }
    @JsonGetter("state")
    public String getState() {
        return this.state;
    }
    @JsonSetter("country")
    public void setCountry(String country) {
        this.country = country;
    }
    @JsonGetter("country")
    public String getCountry() {
        return this.country;
    }
    @JsonSetter("coordinate")
    public void setCoordinate(JobCoordinate coordinate) {
        this.coordinate = coordinate;
    }
    @JsonGetter("coordinate")
    public JobCoordinate getCoordinate() {
        return this.coordinate;
    }
}
