/**
 * MessageException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import app.sdkgen.client.Exception.KnownStatusCodeException;

public class MessageException extends KnownStatusCodeException {

    private Message payload;

    public MessageException(Message payload) {
        super("The server returned an error");

        this.payload = payload;
    }

    public Message getPayload() {
        return this.payload;
    }

}
