/**
 * News automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class News {
    private String id;
    private String title;
    private String link;
    private java.time.LocalDateTime updated;

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    @JsonGetter("title")
    public String getTitle() {
        return this.title;
    }

    @JsonSetter("link")
    public void setLink(String link) {
        this.link = link;
    }

    @JsonGetter("link")
    public String getLink() {
        return this.link;
    }

    @JsonSetter("updated")
    public void setUpdated(java.time.LocalDateTime updated) {
        this.updated = updated;
    }

    @JsonGetter("updated")
    public java.time.LocalDateTime getUpdated() {
        return this.updated;
    }
}

