/**
 * ResponseException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import app.sdkgen.client.Exception.KnownStatusCodeException;

public class ResponseException extends KnownStatusCodeException {

    private Response payload;

    public ResponseException(Response payload) {
        super("The server returned an error");

        this.payload = payload;
    }

    public Response getPayload() {
        return this.payload;
    }

}
