/**
 * State automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class State {
    @JsonProperty("id")
    private String id;

    @JsonProperty("name")
    private String name;

    @JsonPropertyDescription("Size of the area in km2")
    @JsonProperty("area")
    private Integer area;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setArea(Integer area) {
        this.area = area;
    }

    public Integer getArea() {
        return this.area;
    }
}

