/**
 * SystemAboutApps automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

public class SystemAboutApps extends java.util.HashMap<String, String> {
}

