/**
 * WarningCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class WarningCollection {
    private List<Warning> entries;
    @JsonSetter("entries")
    public void setEntries(List<Warning> entries) {
        this.entries = entries;
    }
    @JsonGetter("entries")
    public List<Warning> getEntries() {
        return this.entries;
    }
}
