/**
 * Warning automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package dev.deutschlandapi.sdk;

import com.fasterxml.jackson.annotation.*;

public class Warning {
    @JsonProperty("id")
    private String id;

    @JsonProperty("severity")
    private String severity;

    @JsonProperty("urgency")
    private String urgency;

    @JsonProperty("type")
    private String type;

    @JsonProperty("title")
    private String title;

    @JsonProperty("startDate")
    private java.time.LocalDateTime startDate;

    @JsonProperty("expiresDate")
    private java.time.LocalDateTime expiresDate;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public String getSeverity() {
        return this.severity;
    }

    public void setUrgency(String urgency) {
        this.urgency = urgency;
    }

    public String getUrgency() {
        return this.urgency;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getType() {
        return this.type;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return this.title;
    }

    public void setStartDate(java.time.LocalDateTime startDate) {
        this.startDate = startDate;
    }

    public java.time.LocalDateTime getStartDate() {
        return this.startDate;
    }

    public void setExpiresDate(java.time.LocalDateTime expiresDate) {
        this.expiresDate = expiresDate;
    }

    public java.time.LocalDateTime getExpiresDate() {
        return this.expiresDate;
    }
}

